name: Static Analysis

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ '7.4', '8.0', '8.1' ]

    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress
      - name: Execute PHPStan
        run: vendor/bin/phpstan
